version: "3"
services: 
    # nginx:
    #     image: nginx:stable-pkrss/nginx-alpine-x509
    #     ports: 
    #         - "3000:80"
    #     volumes: 
    #         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: . 
        # //Dockerfile path(build the image for the dockerfile with this path)
        ports: 
            - "3000:3000"
        volumes: 
            - ./:/bookmark
            - /bookmark/node_modules
        environment: 
            - PORT=3000
        depends_on: 
            - mongo
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=sanjeev
            - MONGO_INITDB_ROOT_PASSWORD=mypassword
        volumes: 
            - /data/db